# fly.toml app configuration file generated for transit-redis on 2023-06-20T11:14:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "transit-redis"
primary_region = "cdg"

[build]
  image = "flyio/redis:6.2.6"

[mounts]
  source = "redis_server"
  destination = "/data"

[metrics]
  port = 9091
  path = "/metrics"
